### ISSUE TITLE
카카오톡이 설치되어있지 않습니다.

### ISSUE THREAD

**Issue by ghost** [millo-L/react-native-kakao-share-link#1]
안녕하세요 
카카오톡이 설치되어 있지 않으면 웹으로 링크공유는 기능이 없는건지 궁금합니다 :)

**Comment by millo-L** [comment]
안녕하세요. 카카오톡이 설치되어 있지 않을 때 별도로 링크 공유 기능은 없습니다... 에러에 대한 콜백으로 자체적으로 웹뷰나 Linking(react native 공식)을 사용해서 후 처리를 진행하시기를 권장드립니다.
