### ISSUE TITLE
AndroidManifest.xml intent-filter 내에 <data>태그 삽입 시 빌드 실패 이슈

### ISSUE THREAD

**Issue by jake920220** [millo-L/react-native-kakao-share-link#19]
Document에서 제시하는 
<data android:host="kakaolink" android:scheme="kakao{카카오 네이티브 앱키}" />

태그를 넣고 (카카오 APP 키 넣음) 빌드 할 시

Starting: Intent { cmp=com.rnwebview/.MainActivity }
Error type 3
Error: Activity class {com.rnwebview/com.rnwebview.MainActivity} does not exist.

이렇게 에러가 발생합니다.

해당 태그를 제거할 경우 정상적으로 빌드가 됩니다.

프로젝트는 CRA를 이용하여 만들었습니다.

**Comment by millo-L** [comment]
AndroidManifest.xml 파일을 복사해서 보여주시겠어요?? 앱 키 부분은 {앱 키} 라고 적어서 올려주시면 될 것 같아요

**Comment by jake920220** [comment]
> 
![스크린샷 2023-04-03 오후 3 15 28](https://user-images.githubusercontent.com/25470947/229426359-667b1f0f-c548-4fb0-a02d-bc59d00875d9.png)

다음과 같습니다.

**Comment by millo-L** [comment]
기존에 있던 intent-filter를 대체하는 것이 아니고 아래 코드와 같이 코드를 추가해주셔야 합니다.

```diff
         <intent-filter>
             <action android:name="android.intent.action.MAIN" />
             <category android:name="android.intent.category.LAUNCHER" />
         </intent-filter>
+        <intent-filter>
+            <action android:name="android.intent.action.VIEW" />
+            <category android:name="android.intent.category.DEFAULT" />
+            <category android:name="android.intent.category.BROWSABLE" />
+            <data android:host="kakaolink"
+                  android:scheme="kakao{앱키}" />
+        </intent-filter>
```
